<a href="https://colab.research.google.com/github/Tahan402/DailyPractice/blob/main/Lecture_35_Duplicates_in_DataFrames_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
dframe = pd.DataFrame({'key1':['A']*2 + ['B']*3 , 
                       'key2':[2,2,2,3,3]})

dframe

  key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [4]:
dframe.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [5]:
dframe.drop_duplicates() # for drop duplicates row

  key1  key2
0    A     2
2    B     2
3    B     3

In [7]:
dframe.drop_duplicates(['key1']) #for drop duplicates column

  key1  key2
0    A     2
2    B     2

In [8]:
dframe

  key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [10]:
#dframe.drop_duplicates(['key1'],take_last= True#)